class Device < ActiveRecord::Base
  GCM_URL = 'https://gcm-http.googleapis.com/gcm/send'

  # Length is 152 as that is the length of the tokens
  # that are being generated by Google's servers
  validates :gcm_token, length: { is: 152 }, presence: true
  
  belongs_to :worker

  def call
    # Set the sent parameters
    # As of now most of them are hardcoded for testing purposes
    params = {
      data:{
        token: self.token,
        time: Time.now,
        submission_interval: 60000,
        alarm_time: 60000,
        id: self.id
      },
      to: self.token
    }.to_json

    # Create https connction object
    uri = URI.parse(GCM_URL)
    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true
    
    req = Net::HTTP::Post.new(uri.path)

    # Set headers
    req['Content-Type'] = 'application/json'
    req['Authorization'] = "key=#{Figaro.env.PUSH_NOTIFICATION_SEND_KEY}"

    # Make request
    req.body = params
    res = https.request(req)
    puts "Sent token: Response #{res.code} #{res.message}: #{res.body}"
  end
end
