class Device < ActiveRecord::Base
  # Length is 152 as that is the length of the tokens
  # that are being generated by Google's servers
  validates :gcm_token, length: { is: 152 }, presence: true
  
  belongs_to :worker
end
